spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: sell
    password: sellpassword
    url: jdbc:mysql://localhost:3306/sell?characterEncoding=utf-8&useSSL=false
  jackson:
    default-property-inclusion: non_null
  redis:
    host: 127.0.0.1
    post: 6379
server:
  context-path: /sell

wechat:
  mpAppId: wx93bbf4d13a39e447
  mpAppSecret: db306d6905fa5f27a5cf095df774b446
  openAppId: wx6ad144e54af67d87
  openAppSecret: 91a2ff6d38a2bbccfb7e9f9079108e2e
  mchId: 1490559512
  mchKey: l330673934liuhuan330673934198878
  keyPath: /var/cert/apiclient_cert.p12
  notifyUrl: http://sell.huanliu.org/sell/pay/notify
  templateId:
    orderStatus: WB6hUK8jexdSYGP_GlUubzRuPR47fazwZR_gER2opiA

projectUrl:
  wechatMpAuthorize: http://sell.huanliu.org
  wechatOpenAuthorize: http://selladmin.huanliu.org
  sell: http://selladmin.huanliu.org